name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      THE_GRAPH_TOKEN: ${{ secrets.THE_GRAPH_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 10.17.0
      - name: Generate AssemblyScript types
        run: yarn run codegen
      - name: Deploy to Goerli
        run: |
          yarn run prepare:goerli
          yarn run deploy:goerli
      - name: Deploy to Kovan
        run: |
          yarn run prepare:kovan
          yarn run deploy:kovan
      - name: Deploy to Rinkeby
        run: |
          yarn run prepare:rinkeby
          yarn run deploy:rinkeby
      - name: Deploy to Ropsten
        run: |
          yarn run prepare:ropsten
          yarn run deploy:ropsten
      - name: Deploy to Mainnet
        run: |
          yarn run prepare:mainnet
          yarn run deploy:mainnet
